### ISSUE TITLE
Complete removing cookies panel

### ISSUE THREAD

**Issue by jakubboucek** [jakubboucek/fucking-eu-cookies#14]
**Je naplánováno ukončení provozu této lišty.** Důvody jsou dva:

1. Provoz hostingu lišty platím ze své kapsy a není to levná sranda (viz #12),
2. v návaznosti na GDPR vydalo ÚOOÚ nové stanovisko (viz dále).

Lištu klidně používejte dál, pokud je pro Vás důležitá, jen si ji musíte zkopírovat na svůj web (viz níže).

## Podrobnosti
Úřad pro ochranu osobních údajů [ve svém včerejším doporučení](https://www.uoou.cz/cookies-a-nbsp-gdpr/d-29966) představil nové pojetí pohledu na Cookies ve vztahu k ochraně osobních údajů, ze kterého vyplývá, že tato lišta již není potřeba pro drtivou většinu jejích reálných implementací.

Po dobu provozu jsem různými způsoby monitoroval, jakým způsobem je lišta používána – pouze jeden web použil pokročilé možnosti lišty, kterými skutečně podmínil sbírání údajů o uživatelích. Všechny ostatní implementace považuju nyní za nadbytečné a postrádající smysl, protože neplní žádnou užitečnou funkci, ani zákonné nařízení a pouze obtěžují uživatele.

Další informace na serveru e-legal: [Úřad pro ochranu osobních údajů prolomil mlčení ohledně cookies](http://www.e-legal.cz/clanky/urad-pro-ochranu-osobnich-udaju-prolomil-mlceni-ohledne-cookies)

Z tohoto důvodu jsem se rozhodl ukončit existenci této lišty. Lišta nyní bude zobrazovat upozornění a ke dni 1. 9. 2018 bude z hostingu odstraněna.

### Harmonogram ukončení
- [x] Od 23. 5. 2018: jemné upozornění (#15) s odkazem na tuto issue
- [x] Od 1. 6. 2018: viditelnější upozornění (#16 - změna ikonky na výrazně červenou + varování přes [`console.warn()`](https://developer.mozilla.org/en-US/docs/Web/API/Console/warn))
- [x] Od 1. 7. 2018: logování varování pomocí [`console.error()`](https://developer.mozilla.org/en-US/docs/Web/API/Console/error) (#17)
- [x] Od 1. 9. 2018: vypnutí lišty – místo zobrazení bude kód logovat chybu přes [`console.error()`](https://developer.mozilla.org/en-US/docs/Web/API/Console/error) a současně vyhodí [`throw Error`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) (#18)
- [x] Od 1. 1. 2019: vypnutí CDN a změna S3 bucketu na privátní (bude vracet chybu 403).

## Stažení původní funkční lišty
Pokud však z nějakého důvodu trváte na použití této lišty, stahněte si lištu ze [stránky poslední funkční verze lišty](https://github.com/jakubboucek/fucking-eu-cookies/releases/latest). Případně můžete využít neoficiální fork na CDN (nejsem autorem): https://cdn.jsdelivr.net/npm/eu-cookie-law

Jsem otevřen diskuzi, pokud jste jiného názoru. Chcete-li sledovat vývoj, přihlaste si odběr tohoto vlákna (Subscribe).

**Comment by kamtcho** [comment]
Zdravim. 

No mne to pride prave tak ako doteraz co sa listy tyka + samostatna stranka:

OUUO ked citam: Užití pouze
vyskakujícího okna nebo lišty nelze vždy doporučit. Z tejto vety mi pride, ze nie ze listu nie, ale nie LEN listu. A teda listu ano s kratkym popiskom a odklik na stranku asi bohuzial mi z tohto vychadza. Skor asi mysleli ze nie 10cm listu na vysku s komplet vysvetlenim ale ako je teraz len jedna veta + odklik.

**Comment by jakubboucek** [comment]
@kamtcho Ano, problém je komplexní a tato lišta ho v zásadě nijak neřeší.

Pro cookies, které jsou nezbytné pro provoz aplikace (přihlášení) a pro běžné sledování návštěvnosti (Google Analytics bez zapnutého sledování demografických údajů ap.) **není takového upozornění třeba**, uživatel ho může ovlivnit nastavením cookies ve svém počítači, jak právě potvrdil ÚOOÚ.

Naopak, pokud je sběr dat většího rozsahu, **tak naopak lišta nestačí**, je třeba infomovat o tom uživatele mnohem hlouběji. A především **nesmí být sběr dat zapnutý před udělením souhlasu uživatelem**. Tuto funkčnost sice lišta umí poskytnout ([callback](https://github.com/jakubboucek/fucking-eu-cookies#callback-a-propojen%C3%AD-s-google-tag-manager)), ale je to komplikované a podle analýzy, kterou jsem si dělal koncem března to používal jeden web – s jeho provozovatele jsem se už domluvil.

Tedy nevidím důvod, aby ta lišta dál existovala a prudila uživatele.

**Comment by kamtcho** [comment]
Ja sa opsravedlnujem ale nevidim to prave v tom prohlaseni od UOOU. Nic co by nasvedcovalo ze listu netreba, prave sa mi zda ze lista bude tak ako doteraz. Aj na FB co je skupina sa toto riesili a viac ludi doslo k podobnemu zaveru, no nepresviedcam ,len to sledujem a pisem k comu som dosiel, samozrejme by som aj ja uvital jednoduchsie riesenie.

Mam na mysli tento dokument: https://www.uoou.cz/assets/File.ashx?id_org=200144&id_dokumenty=29973

ta diskusia je tu:
https://www.facebook.com/groups/gdprczmkt/permalink/1666777013430237/

A este kuknite ako to ma cookiebot, ma opt out moznosti dalsie ako sme si mysleli este pred stanoviskom od UOOU ze to tak ma byt.
https://www.cookiebot.com/en/gdpr-cookies/

ak mate este nejaky dalsi prosim dajte vediet.

Dakujem

**Comment by rebendajirijr** [comment]
To je dobry chaos.

V [odkazovanem clanku](https://www.e-legal.cz/aktuality/urad-pro-ochranu-osobnich-udaju-prolomil-mlceni-ohledne-cookies) se zaroven uvadi, ze prohlaseni UOOU neni pravne zavazne.

Samotny web UOOU ma na svem webu klasickou cookie listu 
![image](https://user-images.githubusercontent.com/3431185/40510354-bd0859f0-5f9c-11e8-9f8e-0fb53500a5ad.png), a na ni pouze odkazuji na dodatecne info https://www.uoou.cz/vismo/o-webu.asp#cookies. Jeste vtipnejsi je, ze datum posledni aktualizace tohoto dokumentu je 13. 12. 2012.

V rozporu s tim jsou clanky na cookiebot, ktere deklaruji, ze je vyzadovan predchozi explicitni souhlas uzivatele, bez ktereho se cookie nesmi vubec zacit ukladat.

**Comment by jakubboucek** [comment]
Chaos to je. To je pravda. :-( 

@kamtcho Vyjádření Cookiebot beru velmi s rezervou, protože ten si na tom postavil byznys a touhle úpravou se mu zmaří investice – takže má přirozenou snahu si svoje ovečky udržet.

**Comment by rebendajirijr** [comment]
@jakubboucek ja to zkousel v normalnim i anonymnim okne ve FF a objevuje se mi:
![image](https://user-images.githubusercontent.com/3431185/40511007-b70a831e-5f9e-11e8-8ce0-0646b99f333c.png)

**Comment by jakubboucek** [comment]
@rebendajirijr Už vidím, moje chyba. Ale myslím, že to není relevantní – což naznačuje i datum poslední úpravy toho dokumentu k roku 2012. Ale to je jen můj názor. 

Zatím čekám na další vývoj, abych vůbec stanovil datum, ke kterému bude lišta vypnuta. Na ePrivacy rozhodně nechci čekat.

**Comment by morovan** [comment]
V Harmonograme ukončení bude od 1. 6. posielať varovanie window.warn(), tak dúfam že je tým myslené console.warn() a nie alert :)

**Comment by jakubboucek** [comment]
@morovan [Ano, samozřejmě](https://github.com/jakubboucek/fucking-eu-cookies/pull/16/commits/a1dcf4f6cf0768b9883adf99ebab517443c6d50d#diff-eba89c0ad8dc5878290e1f25efa83cacR153) :-D Díky za upozornění, hned opravím

**Comment by ondrejsika** [comment]
Proc to nehostovat na Github Pages? To je zdarmam ;)

**Comment by jakubboucek** [comment]
@ondrejsika Protože jsem především názoru, že tenhle projekt se stane brzy zbytečným (definitvně o tom rozhodne až ePrivacy). Nechci lidem podruhé říkat, aby se na ~1000 webech měnili URL na GPages ([už jsme si tím prošli jednou](https://github.com/jakubboucek/fucking-eu-cookies/commit/868c55138b3104f4c90eb9abef529b185c641f82) a byla to chyba), když nevím, zda to nebude naposed (což nevím, vzhledem k tomu, že [právě dneska se řeší kauza](https://twitter.com/JakubBoucek/status/1002866381635891201), že Github bude pohlcen MIcrosoftem).

**Comment by jakubboucek** [comment]
Za 15 dní se lišta bude vypínat. Do té doby bude na [této stránce](https://s3-eu-west-1.amazonaws.com/fucking-eu-cookies/beta/index.html) viditelná plánovaná verze lišty, jak je připravena v #18. Tedy nic se nezobrazuje, pouze to hází JS chyby do konzole.

U sebe jsem otestoval, že vyhozená výjimka nezabije jiné kusy Javascriptu ve stránce. Tedy za předpokladu, že je volána tak, jak je v dokumentaci. Pokud si to někdo umotal jiným způsobem, tak to může jeho script ovlivnit. Nicméně v takovém případě to úplně stejně rozbije i plánované vypnutí hostingu na konci roku, tak proto to neplánuju zohledňovat.

Ale můžu se mýlit a budu rád za věcnou kritiku.

**Comment by MartinN3** [comment]
Mohli bychom dostat nějaké statistiky počtu requestů a nákladovou položku? Myslím, že by to mohlo být zajímavé a poučné. Díky za vyjádření.

**Comment by jakubboucek** [comment]
@MartinN3 Popsal jsem to v #12, ale máte nějaké konkrétní otázky?

**Comment by jakubboucek** [comment]
Panel je odpojen.
